name: Release NPM package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci --no-audit
      - run: npm run build
      - run: cp -R ./build ./dist && cp *.md LICENSE ChangeLog package*.json ./dist | true
      - run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}