name: Syntax tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Syntax tests
    steps:
    - uses: actions/checkout@v3
    - name: Testing syntax
      uses: actions/setup-node@v3
      with:
        node-version: 17.x
        architecture: x64
        cache: 'npm'
    - run: npm ci --no-audit || npm install
    - run: npm run build
    - run: npm run test:syntax
