# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
#          - ubuntu-18.04
          - ubuntu-20.04
#          - windows-2016
          - windows-2019
        node-version: [12.x, 13.x, 14.x, 15.x, 16.x, 17.x, 18.x]
        architecture:
          #- x86
          - x64
          #- arm64
          #- armv6l
          #- armv7l
#        include:
#           - os: ubuntu-20.04
#             node-version: 14.x
#             architecture: arm64
#           - os: ubuntu-20.04
#             node-version: 16.x
#             architecture: arm64

    name: Unit tests with Node ${{ matrix.node-version }} on ${{ matrix.os }} ${{ matrix.architecture }}
    steps:
    - uses: actions/checkout@v2
    - name: Testing using Node.JS ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        architecture: ${{ matrix.architecture }}
        cache: 'npm'
    - run: npm ci || npm install
    - run: npm run build
    - run: npm run test:unit
